data_root: /home/rlsa/mg/LibFewShot-FD-Align/datasets/caltech-101
image_size: 224
use_memory: False
augment: True
augment_method: FD_Align
augment_times: 1
augment_times_query: 1
workers: 1 # number of workers for dataloader in all threads
dataloader_num: 1
