epoch: 10
test_epoch: 1

parallel_part:
  - emb_func

pretrain_path: ~
resume: False
# few shot settings
way_num: 5
shot_num: 1
query_num: 15
test_way: ~ # use ~ -> test_* = *_num
test_shot: ~
test_query: ~
episode_size: 1
train_episode: 1000
test_episode: 200

# general model setting
batch_size: 100
val_per_epoch: 1
