includes:
  - headers/data.yaml
  - headers/device.yaml
  - headers/misc.yaml
  - headers/model.yaml
  - headers/optimizer.yaml
  - classifiers/CLIP_context_only_CoOp.yaml
  - backbones/clip.yaml

# pretrain_path: datasets/pretrain_model/ViT-B-32.pt

classifier:
  name: CLIP_context_only_CoOP
  kwargs:
    backbone_name: ViT_B_32
    cname: caltech101

backbone:
  name: clip
  kwargs: ~